export const privacyData = [
  {
    id: 1,
    title: "GENERAL INFORMATION",
    description: `
        <p class="py-2">PSEA does not capture and store any personal information about individuals who access this website, except where you voluntarily choose to give us your personal details or by enquiring about or ordering any of our services.
        </p>
        `,
  },
  {
    id: 2,
    title: "TYPES OF INFORMATION GATHERED",
    description: `
        <p class="py-2">The information we collect from our users helps us to effectively provide our services and to personalise and continually improve the user experience on the website. These are the types of information we collect:
        </p>
        <p class="py-2"><b>Information You Give Us.</b> You provide information when you connect your virtual wallet, purchase NFTs, purchase products (digital and physical), create a derivative work from purchased NFTs and/or communicate with us through our contact information or our contact forms. As a result of those actions, you might supply us with the following information:
        </p>
        <ul class="list-disc pl-5 my-6 flex flex-col gap-4">
        <li>User content
        </li>
        <li>Virtual wallet information        </li>
        <li>Any additional information relating to you that you provide to us directly through our website or indirectly through our website or online presence such as ‘cookies’.
        </li>
        </ul>
        <p class="py-2">PSEA will not collect any personally identifiable information about you, unless you provide it.
        </p>
        <p class="py-2"><b>Information Collected Automatically: </b> By accessing and using the website you automatically provide us with the following information:
        </p>
        <ul class="list-disc pl-5 my-6 flex flex-col gap-4">
        <li>The device and usage information you use to access the website
        </li>
        <li>The device and usage information you use to access the website
        </li>
        <li>Browser and device characteristics
        </li>
        <li>Operating system
        </li>
        <li>Referring URLs
        </li>
        <li>Your location
        </li>
        <li>What parts of the website you use and how often
        </li>
        </ul>
        <p class="py-2">If you access the website through a mobile phone, we will collect the following information:
        </p>
        <ul class="list-disc pl-5 my-6 flex flex-col gap-4">
        <li>Mobile device ID 
        </li>
        <li>Model and manufacturer 
        </li>
        <li>Operating system 
        </li>
        <li>Version information 
        </li>
        <li>IP address
        </li>
        </ul>
        <p class="py-2"><b>Payment information:</b> Transaction information will be processed through the Blockchain system. Transaction data will be processed and stored securely and for the sole purpose of processing transactions within the platform, using standard security methods of the blockchain system. PSEA reserves the right to contract any payment platform available on the market, which will process your data for the sole purpose of processing transactions within the platform.
        </p>
        <p class="py-2"><b>Google Analytics.</b> We use Google Analytics provided by Google, Inc., USA (“Google”). These tool and technologies collect and analyse certain types of information, including IP addresses, device and software identifiers, referring and exit URLs, feature use metrics and statistics, usage and purchase history, media access control address (MAC Address), mobile unique device identifiers, and other similar information via the use of cookies. The information generated by Google Analytics (including your IP address) may be transmitted to and stored by Google on servers in the United States. We use the Google Analytics collection of data to enhance the website and improve our service.
        </p>
        <p class="py-2">Please consult Google's privacy policy here:
        </p>
        <ul class="list-disc pl-5 my-6 flex flex-col gap-4"><li>
        <a class="text-sea-red-400" href="https://policies.google.com/privacy">https://policies.google.com/privacy</a>
        </li></ul>
        `,
  },
  {
    id: 3,
    title: "HOW LONG WE KEEP YOUR DATA",
    description: `
        <p class="py-2">Personal data provided by users through the website and services will be retained for as long as necessary to provide our services within the website (sale of NFTs, sale of physical and digital products, creation of artwork derived from NFTs, etc.) or until the user decides to close the user account or PSEA decides to close the user account. PSEA may be allowed to retain personal data for a longer period whenever the user has given consent to such processing, as long as such consent is not withdrawn. Furthermore, PSEA may be obliged to retain personal data for a longer period whenever required to do so for the performance of a legal obligation or upon order of an authority. Once the retention period expires, personal data shall be deleted. Therefore, the right to access, the right to erasure, the right to rectification and the right to data portability cannot be enforced after expiration of the retention period.
        </p>
        `,
  },
  {
    id: 4,
    title: "HOW WE USE YOUR INFORMATION.",
    description: `
        <p class="py-2">In general, we use the information we collect primarily to provide, maintain, protect and improve our current website and services. We use personal information collected through our website as described below:
        </p>
        <ul class="list-disc pl-5 my-6 flex flex-col gap-4">
        <li>Identify you as a user in our system.
        </li>
        <li>User registration.
        </li>
        <li>Provide NFTs (purchase and sale of NFTs).
        </li>
        <li>Facilitate the creation of artwork derived from the NFTs.
        </li>
        <li>Provide physical and digital products.
        </li>
        <li>Process transactions within the website.
        </li>
        <li>Connect user wallets (Ethereum). 
        </li>
        <li>Improve our services, website, and how we operate our business.
        </li>
        <li>Understand and enhance your experience using our website and services.
        </li>
        <li>Respond to your comments or questions through our support team.
        </li>
        <li>Send you related information, including confirmations, invoices, technical notices, updates, security alerts and support and administrative messages.
        </li>
        <li>Communicate with you about upcoming events and news about services offered by PSEA and our selected partners.
        </li>
        <li>Marketing purposes of PSEA.
        </li>
        <li>Protect, investigate and deter against fraudulent, unauthorised or illegal activity.
        </li>
        </ul>
        `,
  },
  {
    id: 5,
    title: "HOW DO YOU GET MY CONSENT?",
    description: `
        <p class="py-2">By connecting your wallet, purchasing NFTs, purchasing products (physical and digital), creating artwork derived from NFTs, communicating with us through contact forms or contact information and providing us with personal information to communicate with you, you consent to our collection, storage and use of your information on the terms contained in this privacy policy. You may withdraw your consent by sending us your request via the contact information or the contact page.
        </p>
        `,
  },
  {
    id: 6,
    title: "HOW WE SHARE INFORMATION",
    description: `
        <p class="py-2">The personal information of our customers and users is an important and fundamental part of our business. Under no circumstances will we sell or share information with third parties that has not been previously authorised by the user, customer or owner of the personal data. We share user and customer information only and exclusively as described below.
        </p>
        <p class="py-2"><b>Third-Party Service Providers.</b> We use third-party services to perform certain functions on our behalf and through our website and services. We use these third-party services: create and host the website, send emails, analyse data (Google Analytics), provide marketing assistance, and provide website search results.
        </p>
        <p class="py-2">These third-party services and tools may have access to personal information needed to perform their functions, but may not use that information for other purposes. Information shared with these third-party services will be treated and stored in accordance with their respective privacy policies and our privacy policy. Please refer to the privacy policy of these third-party services.
        </p>
        <p class="py-2"><b>Business Transfers.</b> In the event that PSEA creates, merges with, or is acquired by another entity, your information will most likely be transferred. PSEA will email you or place a prominent notice on our website before your information becomes subject to another privacy policy.
        </p>
        <p class="py-2"><b>Protection of PSEA and others.</b> We release personal information when we believe release is appropriate to comply with the law, enforce or apply our Terms and conditions and other agreements, or protect the rights, property, or safety of PSEA, our users or others. This includes exchanging information with other companies and organisations for fraud protection and credit risk reduction.
        </p>
        <p class="py-2"><b>With Your Consent.</b> Other than as set out above, you will receive notice when personally identifiable information about you might go to third parties, and you will have an opportunity to choose not to share the information.
        </p>
        <p class="py-2"><b>Anonymous Information.</b> PSEA uses the anonymous browsing information collected automatically by our servers primarily to help us administer and improve the website. We may also use aggregated anonymous information to provide information about the website to potential business partners and other unaffiliated entities. This information is not personally identifiable.
        </p>
       
        `,
  },
  {
    id: 7,
    title: "PROTECTING YOUR INFORMATION",
    description: `
        <p class="py-2">We work to protect the security of your information during transmission by using Secure Sockets Layer (SSL) software, which encrypts information you provide through the website and platform. If transactions are processed on the website, transaction information is transmitted to and from the platform in encrypted form using industry-standard SSL connections to help protect such information from interception. We restrict authorised access to your personal information to those persons who have a legitimate need to know that information and to those persons you have authorised to have access to that information. PSEA follows generally accepted industry standards to protect the personal information submitted to us, both during transmission and once PSEA receives it. No method of transmission over the Internet, or method of electronic storage, is 100% secure. Therefore, while PSEA strives to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security. We will not sell, distribute or lease your personal information to third parties unless we have your permission or are required by law to do so.
        </p>
        `,
  },
  {
    id: 8,
    title: "RIGHTS",
    description: `
        <p class="py-2">Users who provide information through our website, as data subjects and data owners, have the right to access, rectify, download or delete their information, as well as to restrict and object to certain processing of their information. While some of these rights apply generally, others apply only in certain limited circumstances. We describe these rights below:
        </p>
        <ul class="list-disc pl-5 my-6 flex flex-col gap-4">
        <li><b>Access and portability:</b> to access and know what information is stored in our servers, you can send us your request through our contact information.

        </li>
        <li><b>Rectify, Restrict, Limit and/or Delete:</b> You can also rectify, restrict, limit or delete much of your information.
        </li>
        <li><b>Right to be informed:</b> Users of our website will be informed, upon request, about what data we collect, how it is used, how long it is retained and whether it is shared with third parties.
        </li>
        <li><b>Object:</b> When we process your information based on our legitimate interests as explained above, or in the public interest, you may object to this processing in certain circumstances. In such cases, we will stop processing your information unless we have compelling legitimate reasons to continue processing it or where it is necessary for legal reasons.
        </li>
        <li><b>Revoke consent:</b> Where you have previously given your consent, such as to allow us to process and store your personal information, you have the right to revoke your consent to the processing and storage of your information at any time. For example, you may withdraw your consent by updating your settings. In certain cases, we may continue to process your information after you have withdrawn your consent if we have a legal basis for doing so or if your withdrawal of consent was limited to certain processing activities.
        </li>
        <li><b>Complaint:</b> If you wish to file a complaint about our use of your information (and without prejudice to any other rights you may have), you have the right to do so with your local supervisory authority. Users can exercise all these rights by contacting us through the contact information or the contact page.
        </li>
        <li><b>Rights related to automated decision-making, including profiling:</b> website users may request that we provide a copy of the automated processing activities we conduct if they believe that data is being unlawfully processed.
        </li>
        </ul>
        <p class="py-2">Users or owners of the personal information they provide through the website and services may exercise these rights over their personal information at any time and without any limitation by sending us their request through our contact information.
        </p>
        `,
  },
  {
    id: 9,
    title: "CHILDREN’S ONLINE PRIVACY PROTECTION",
    description: `
        <p class="py-2">We comply with the requirements of personal data protection regulations, regarding the protection of the personal data of minors. We do not collect any information from anyone under 13 years of age. Our website and services are all directed to people who are at least 13 years old or older. If you become aware that your child has provided us with personal information, please contact us. If we become aware that a child has provided us with personal information, we will take steps to delete that information, terminate that person's account, and restrict access to that person.
        </p>
        `,
  },
  {
    id: 10,
    title: "THIRD PARTIES",
    description: `
        <p class="py-2">Except as otherwise expressly included in this privacy policy, this document addresses only the use and disclosure of information PSEA collects from you. If you disclose your information to others, whether other users or suppliers on PSEA, different rules may apply to their use or disclosure of the information you disclose to them. PSEA does not control the privacy policies of third parties, and you are subject to the privacy policies of those third parties where applicable. PSEA is not responsible for the privacy or security practices of other websites on the Internet, even those linked to or from the PSEA website. PSEA encourages you to ask questions before you disclose your personal information to others.</p>
        `,
  },
];
